; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;; Test that checks all variants of ndrange and what ndrange_1D, ndrange_2D and ndrange_3D can coexist in the same module
;;
;; bash$ cat BuildNDRange.cl
;; void test_ndrange_2D3D() {
;;   size_t GS1 = 1;
;;   size_t LS1 = 2;
;;   size_t WO1 = 3;
;;   ndrange_1D(GS1);
;;   ndrange_1D(GS1, LS1);
;;   ndrange_1D(WO1, GS1, LS1);
;;   ndrange_1D(GS1, GS1);
;;   ndrange_1D(GS1, GS1, GS1);
;;   size_t GS2[2] = {1, 1};
;;   size_t LS2[2] = {2, 2};
;;   size_t WO2[2] = {3, 3};
;;   ndrange_2D(GS2);
;;   ndrange_2D(GS2, LS2);
;;   ndrange_2D(WO2, GS2, LS2);
;;   ndrange_2D(GS2, GS2);
;;   ndrange_2D(GS2, GS2, GS2);
;;   size_t GS3[3] = {1, 1, 1};
;;   size_t LS3[3] = {1, 2, 1};
;;   size_t WO3[3] = {1, 3, 1};
;;   ndrange_3D(GS3);
;;   ndrange_2D(GS3, LS3);
;;   ndrange_2D(WO3, GS3, LS3);
;;   ndrange_2D(GS3, GS3);
;;   ndrange_2D(GS3, GS3, GS3);
;;   const size_t GS1c = 1;
;;   const size_t LS1c = 2;
;;   const size_t WO1c = 3;
;;   ndrange_1D(GS1c);
;;   ndrange_1D(GS1c, LS1c);
;;   ndrange_1D(WO1c, GS1c, LS1c);
;;   ndrange_1D(GS1c, GS1c);
;;   ndrange_1D(GS1c, GS1c, GS1c);
;;   const size_t GS2c[2] = {1, 1};
;;   const size_t LS2c[2] = {1, 2};
;;   const size_t WO2c[2] = {1, 3};
;;   ndrange_2D(GS2c);
;;   ndrange_2D(GS2c, LS2c);
;;   ndrange_2D(WO2c, GS2c, LS2c);
;;   ndrange_2D(GS2c, GS2c);
;;   ndrange_2D(GS2c, GS2c, GS2c);
;;   const size_t GS3c[3] = {1, 1, 1};
;;   const size_t LS3c[3] = {1, 1, 2};
;;   const size_t WO3c[3] = {1, 1, 3};
;;   ndrange_3D(GS3c);
;;   ndrange_2D(GS3c, LS3c);
;;   ndrange_2D(WO3c, GS3c, LS3c);
;;   ndrange_2D(GS3c, GS3c);
;;   ndrange_2D(GS3c, GS3c, GS3c);
;; }
;; bash$ clang -cc1  -cl-std=CL2.0 -triple spirv64-unknown-unknown -emit-llvm -finclude-default-header -cl-single-precision-constant BuildNDRange.cl -o BuildNDRange.ll


; RUN: llc -O0 -mtriple=spirv64-unknown-unknown %s -o - | FileCheck %s
; %if spirv-tools %{ llc -O0 -mtriple=spirv64-unknown-unknown %s -o - -filetype=obj | spirv-val %}

%struct.ndrange_t = type { i32, [3 x i64], [3 x i64], [3 x i64] }

@__const.test_ndrange_2D3D.GS2 = private unnamed_addr addrspace(2) constant [2 x i64] [i64 1, i64 1], align 8
@__const.test_ndrange_2D3D.LS2 = private unnamed_addr addrspace(2) constant [2 x i64] [i64 2, i64 2], align 8
@__const.test_ndrange_2D3D.WO2 = private unnamed_addr addrspace(2) constant [2 x i64] [i64 3, i64 3], align 8
@__const.test_ndrange_2D3D.GS3 = private unnamed_addr addrspace(2) constant [3 x i64] [i64 1, i64 1, i64 1], align 8
@__const.test_ndrange_2D3D.LS3 = private unnamed_addr addrspace(2) constant [3 x i64] [i64 1, i64 2, i64 1], align 8
@__const.test_ndrange_2D3D.WO3 = private unnamed_addr addrspace(2) constant [3 x i64] [i64 1, i64 3, i64 1], align 8
@__const.test_ndrange_2D3D.GS2c = private unnamed_addr addrspace(2) constant [2 x i64] [i64 1, i64 1], align 8
@__const.test_ndrange_2D3D.LS2c = private unnamed_addr addrspace(2) constant [2 x i64] [i64 1, i64 2], align 8
@__const.test_ndrange_2D3D.WO2c = private unnamed_addr addrspace(2) constant [2 x i64] [i64 1, i64 3], align 8
@__const.test_ndrange_2D3D.GS3c = private unnamed_addr addrspace(2) constant [3 x i64] [i64 1, i64 1, i64 1], align 8
@__const.test_ndrange_2D3D.LS3c = private unnamed_addr addrspace(2) constant [3 x i64] [i64 1, i64 1, i64 2], align 8
@__const.test_ndrange_2D3D.WO3c = private unnamed_addr addrspace(2) constant [3 x i64] [i64 1, i64 1, i64 3], align 8

define spir_func void @test_ndrange_2D3D() local_unnamed_addr #0 {
; CHECK-LABEL: test_ndrange_2D3D
; CHECK:       %50 = OpFunction %3 None %4 ; -- Begin function test_ndrange_2D3D
; CHECK-NEXT:    %2 = OpLabel
; CHECK-NEXT:    %51 = OpVariable %10 Function
; CHECK-NEXT:    %52 = OpVariable %10 Function
; CHECK-NEXT:    %53 = OpVariable %10 Function
; CHECK-NEXT:    %54 = OpVariable %10 Function
; CHECK-NEXT:    %55 = OpVariable %10 Function
; CHECK-NEXT:    %56 = OpVariable %13 Function
; CHECK-NEXT:    %57 = OpVariable %13 Function
; CHECK-NEXT:    %58 = OpVariable %13 Function
; CHECK-NEXT:    %59 = OpVariable %10 Function
; CHECK-NEXT:    %60 = OpVariable %10 Function
; CHECK-NEXT:    %61 = OpVariable %10 Function
; CHECK-NEXT:    %62 = OpVariable %10 Function
; CHECK-NEXT:    %63 = OpVariable %10 Function
; CHECK-NEXT:    %64 = OpVariable %16 Function
; CHECK-NEXT:    %65 = OpVariable %16 Function
; CHECK-NEXT:    %66 = OpVariable %16 Function
; CHECK-NEXT:    %67 = OpVariable %10 Function
; CHECK-NEXT:    %68 = OpVariable %10 Function
; CHECK-NEXT:    %69 = OpVariable %10 Function
; CHECK-NEXT:    %70 = OpVariable %10 Function
; CHECK-NEXT:    %71 = OpVariable %10 Function
; CHECK-NEXT:    %72 = OpVariable %10 Function
; CHECK-NEXT:    %73 = OpVariable %10 Function
; CHECK-NEXT:    %74 = OpVariable %10 Function
; CHECK-NEXT:    %75 = OpVariable %10 Function
; CHECK-NEXT:    %76 = OpVariable %10 Function
; CHECK-NEXT:    %77 = OpVariable %13 Function
; CHECK-NEXT:    %78 = OpVariable %13 Function
; CHECK-NEXT:    %79 = OpVariable %13 Function
; CHECK-NEXT:    %80 = OpVariable %10 Function
; CHECK-NEXT:    %81 = OpVariable %10 Function
; CHECK-NEXT:    %82 = OpVariable %10 Function
; CHECK-NEXT:    %83 = OpVariable %10 Function
; CHECK-NEXT:    %84 = OpVariable %10 Function
; CHECK-NEXT:    %85 = OpVariable %16 Function
; CHECK-NEXT:    %86 = OpVariable %16 Function
; CHECK-NEXT:    %87 = OpVariable %16 Function
; CHECK-NEXT:    %88 = OpVariable %10 Function
; CHECK-NEXT:    %89 = OpVariable %10 Function
; CHECK-NEXT:    %90 = OpVariable %10 Function
; CHECK-NEXT:    %91 = OpVariable %10 Function
; CHECK-NEXT:    %92 = OpVariable %10 Function
; CHECK-NEXT:    %93 = OpBitcast %27 %51
; CHECK-NEXT:    OpLifetimeStart %93 80
; CHECK-NEXT:    %94 = OpBuildNDRange %9 %24 %25 %25
; CHECK-NEXT:    OpStore %51 %94
; CHECK-NEXT:    %95 = OpBitcast %27 %51
; CHECK-NEXT:    OpLifetimeStop %95 80
; CHECK-NEXT:    %96 = OpBitcast %27 %52
; CHECK-NEXT:    OpLifetimeStart %96 80
; CHECK-NEXT:    %97 = OpBuildNDRange %9 %24 %23 %25
; CHECK-NEXT:    OpStore %52 %97
; CHECK-NEXT:    %98 = OpBitcast %27 %52
; CHECK-NEXT:    OpLifetimeStop %98 80
; CHECK-NEXT:    %99 = OpBitcast %27 %53
; CHECK-NEXT:    OpLifetimeStart %99 80
; CHECK-NEXT:    %100 = OpBuildNDRange %9 %24 %23 %22
; CHECK-NEXT:    OpStore %53 %100
; CHECK-NEXT:    %101 = OpBitcast %27 %53
; CHECK-NEXT:    OpLifetimeStop %101 80
; CHECK-NEXT:    %102 = OpBitcast %27 %54
; CHECK-NEXT:    OpLifetimeStart %102 80
; CHECK-NEXT:    %103 = OpBuildNDRange %9 %24 %24 %25
; CHECK-NEXT:    OpStore %54 %103
; CHECK-NEXT:    %104 = OpBitcast %27 %54
; CHECK-NEXT:    OpLifetimeStop %104 80
; CHECK-NEXT:    %105 = OpBitcast %27 %55
; CHECK-NEXT:    OpLifetimeStart %105 80
; CHECK-NEXT:    %106 = OpBuildNDRange %9 %24 %24 %24
; CHECK-NEXT:    OpStore %55 %106
; CHECK-NEXT:    %107 = OpBitcast %27 %55
; CHECK-NEXT:    OpLifetimeStop %107 80
; CHECK-NEXT:    %108 = OpBitcast %27 %56
; CHECK-NEXT:    OpLifetimeStart %108 16
; CHECK-NEXT:    OpCopyMemorySized %56 %29 %21 Aligned 8
; CHECK-NEXT:    %109 = OpBitcast %27 %57
; CHECK-NEXT:    OpLifetimeStart %109 16
; CHECK-NEXT:    OpCopyMemorySized %57 %31 %21 Aligned 8
; CHECK-NEXT:    %110 = OpBitcast %27 %58
; CHECK-NEXT:    OpLifetimeStart %110 16
; CHECK-NEXT:    OpCopyMemorySized %58 %33 %21 Aligned 8
; CHECK-NEXT:    %111 = OpBitcast %27 %59
; CHECK-NEXT:    OpLifetimeStart %111 80
; CHECK-NEXT:    %112 = OpLoad %12 %56
; CHECK-NEXT:    %113 = OpBuildNDRange %9 %112 %14 %14
; CHECK-NEXT:    OpStore %59 %113
; CHECK-NEXT:    %114 = OpBitcast %27 %59
; CHECK-NEXT:    OpLifetimeStop %114 80
; CHECK-NEXT:    %115 = OpBitcast %27 %60
; CHECK-NEXT:    OpLifetimeStart %115 80
; CHECK-NEXT:    %116 = OpBitcast %15 %56
; CHECK-NEXT:    %117 = OpBitcast %13 %116
; CHECK-NEXT:    %118 = OpLoad %12 %117
; CHECK-NEXT:    %119 = OpLoad %12 %57
; CHECK-NEXT:    %120 = OpBuildNDRange %9 %118 %119 %14
; CHECK-NEXT:    OpStore %60 %120
; CHECK-NEXT:    %121 = OpBitcast %27 %60
; CHECK-NEXT:    OpLifetimeStop %121 80
; CHECK-NEXT:    %122 = OpBitcast %27 %61
; CHECK-NEXT:    OpLifetimeStart %122 80
; CHECK-NEXT:    %123 = OpBitcast %15 %58
; CHECK-NEXT:    %124 = OpBitcast %13 %116
; CHECK-NEXT:    %125 = OpLoad %12 %124
; CHECK-NEXT:    %126 = OpLoad %12 %57
; CHECK-NEXT:    %127 = OpBitcast %13 %123
; CHECK-NEXT:    %128 = OpLoad %12 %127
; CHECK-NEXT:    %129 = OpBuildNDRange %9 %125 %126 %128
; CHECK-NEXT:    OpStore %61 %129
; CHECK-NEXT:    %130 = OpBitcast %27 %61
; CHECK-NEXT:    OpLifetimeStop %130 80
; CHECK-NEXT:    %131 = OpBitcast %27 %62
; CHECK-NEXT:    OpLifetimeStart %131 80
; CHECK-NEXT:    %132 = OpBitcast %13 %116
; CHECK-NEXT:    %133 = OpLoad %12 %132
; CHECK-NEXT:    %134 = OpLoad %12 %56
; CHECK-NEXT:    %135 = OpBuildNDRange %9 %133 %134 %14
; CHECK-NEXT:    OpStore %62 %135
; CHECK-NEXT:    %136 = OpBitcast %27 %62
; CHECK-NEXT:    OpLifetimeStop %136 80
; CHECK-NEXT:    %137 = OpBitcast %27 %63
; CHECK-NEXT:    OpLifetimeStart %137 80
; CHECK-NEXT:    %138 = OpBitcast %13 %116
; CHECK-NEXT:    %139 = OpLoad %12 %138
; CHECK-NEXT:    %140 = OpLoad %12 %56
; CHECK-NEXT:    %141 = OpBitcast %13 %116
; CHECK-NEXT:    %142 = OpLoad %12 %141
; CHECK-NEXT:    %143 = OpBuildNDRange %9 %139 %140 %142
; CHECK-NEXT:    OpStore %63 %143
; CHECK-NEXT:    %144 = OpBitcast %27 %63
; CHECK-NEXT:    OpLifetimeStop %144 80
; CHECK-NEXT:    %145 = OpBitcast %27 %64
; CHECK-NEXT:    OpLifetimeStart %145 24
; CHECK-NEXT:    OpCopyMemorySized %64 %35 %20 Aligned 8
; CHECK-NEXT:    %146 = OpBitcast %27 %65
; CHECK-NEXT:    OpLifetimeStart %146 24
; CHECK-NEXT:    OpCopyMemorySized %65 %37 %20 Aligned 8
; CHECK-NEXT:    %147 = OpBitcast %27 %66
; CHECK-NEXT:    OpLifetimeStart %147 24
; CHECK-NEXT:    OpCopyMemorySized %66 %39 %20 Aligned 8
; CHECK-NEXT:    %148 = OpBitcast %27 %67
; CHECK-NEXT:    OpLifetimeStart %148 80
; CHECK-NEXT:    %149 = OpLoad %8 %64
; CHECK-NEXT:    %150 = OpBuildNDRange %9 %149 %17 %17
; CHECK-NEXT:    OpStore %67 %150
; CHECK-NEXT:    %151 = OpBitcast %27 %67
; CHECK-NEXT:    OpLifetimeStop %151 80
; CHECK-NEXT:    %152 = OpBitcast %27 %68
; CHECK-NEXT:    OpLifetimeStart %152 80
; CHECK-NEXT:    %153 = OpBitcast %15 %64
; CHECK-NEXT:    %154 = OpBitcast %13 %153
; CHECK-NEXT:    %155 = OpLoad %12 %154
; CHECK-NEXT:    %156 = OpBitcast %13 %65
; CHECK-NEXT:    %157 = OpLoad %12 %156
; CHECK-NEXT:    %158 = OpBuildNDRange %9 %155 %157 %14
; CHECK-NEXT:    OpStore %68 %158
; CHECK-NEXT:    %159 = OpBitcast %27 %68
; CHECK-NEXT:    OpLifetimeStop %159 80
; CHECK-NEXT:    %160 = OpBitcast %27 %69
; CHECK-NEXT:    OpLifetimeStart %160 80
; CHECK-NEXT:    %161 = OpBitcast %15 %66
; CHECK-NEXT:    %162 = OpBitcast %13 %153
; CHECK-NEXT:    %163 = OpLoad %12 %162
; CHECK-NEXT:    %164 = OpBitcast %13 %65
; CHECK-NEXT:    %165 = OpLoad %12 %164
; CHECK-NEXT:    %166 = OpBitcast %13 %161
; CHECK-NEXT:    %167 = OpLoad %12 %166
; CHECK-NEXT:    %168 = OpBuildNDRange %9 %163 %165 %167
; CHECK-NEXT:    OpStore %69 %168
; CHECK-NEXT:    %169 = OpBitcast %27 %69
; CHECK-NEXT:    OpLifetimeStop %169 80
; CHECK-NEXT:    %170 = OpBitcast %27 %70
; CHECK-NEXT:    OpLifetimeStart %170 80
; CHECK-NEXT:    %171 = OpBitcast %13 %153
; CHECK-NEXT:    %172 = OpLoad %12 %171
; CHECK-NEXT:    %173 = OpBitcast %13 %64
; CHECK-NEXT:    %174 = OpLoad %12 %173
; CHECK-NEXT:    %175 = OpBuildNDRange %9 %172 %174 %14
; CHECK-NEXT:    OpStore %70 %175
; CHECK-NEXT:    %176 = OpBitcast %27 %70
; CHECK-NEXT:    OpLifetimeStop %176 80
; CHECK-NEXT:    %177 = OpBitcast %27 %71
; CHECK-NEXT:    OpLifetimeStart %177 80
; CHECK-NEXT:    %178 = OpBitcast %13 %153
; CHECK-NEXT:    %179 = OpLoad %12 %178
; CHECK-NEXT:    %180 = OpBitcast %13 %64
; CHECK-NEXT:    %181 = OpLoad %12 %180
; CHECK-NEXT:    %182 = OpBitcast %13 %153
; CHECK-NEXT:    %183 = OpLoad %12 %182
; CHECK-NEXT:    %184 = OpBuildNDRange %9 %179 %181 %183
; CHECK-NEXT:    OpStore %71 %184
; CHECK-NEXT:    %185 = OpBitcast %27 %71
; CHECK-NEXT:    OpLifetimeStop %185 80
; CHECK-NEXT:    %186 = OpBitcast %27 %72
; CHECK-NEXT:    OpLifetimeStart %186 80
; CHECK-NEXT:    %187 = OpBuildNDRange %9 %24 %25 %25
; CHECK-NEXT:    OpStore %72 %187
; CHECK-NEXT:    %188 = OpBitcast %27 %72
; CHECK-NEXT:    OpLifetimeStop %188 80
; CHECK-NEXT:    %189 = OpBitcast %27 %73
; CHECK-NEXT:    OpLifetimeStart %189 80
; CHECK-NEXT:    %190 = OpBuildNDRange %9 %24 %23 %25
; CHECK-NEXT:    OpStore %73 %190
; CHECK-NEXT:    %191 = OpBitcast %27 %73
; CHECK-NEXT:    OpLifetimeStop %191 80
; CHECK-NEXT:    %192 = OpBitcast %27 %74
; CHECK-NEXT:    OpLifetimeStart %192 80
; CHECK-NEXT:    %193 = OpBuildNDRange %9 %24 %23 %22
; CHECK-NEXT:    OpStore %74 %193
; CHECK-NEXT:    %194 = OpBitcast %27 %74
; CHECK-NEXT:    OpLifetimeStop %194 80
; CHECK-NEXT:    %195 = OpBitcast %27 %75
; CHECK-NEXT:    OpLifetimeStart %195 80
; CHECK-NEXT:    %196 = OpBuildNDRange %9 %24 %24 %25
; CHECK-NEXT:    OpStore %75 %196
; CHECK-NEXT:    %197 = OpBitcast %27 %75
; CHECK-NEXT:    OpLifetimeStop %197 80
; CHECK-NEXT:    %198 = OpBitcast %27 %76
; CHECK-NEXT:    OpLifetimeStart %198 80
; CHECK-NEXT:    %199 = OpBuildNDRange %9 %24 %24 %24
; CHECK-NEXT:    OpStore %76 %199
; CHECK-NEXT:    %200 = OpBitcast %27 %76
; CHECK-NEXT:    OpLifetimeStop %200 80
; CHECK-NEXT:    %201 = OpBitcast %27 %77
; CHECK-NEXT:    OpLifetimeStart %201 16
; CHECK-NEXT:    OpCopyMemorySized %77 %40 %21 Aligned 8
; CHECK-NEXT:    %202 = OpBitcast %27 %78
; CHECK-NEXT:    OpLifetimeStart %202 16
; CHECK-NEXT:    OpCopyMemorySized %78 %42 %21 Aligned 8
; CHECK-NEXT:    %203 = OpBitcast %27 %79
; CHECK-NEXT:    OpLifetimeStart %203 16
; CHECK-NEXT:    OpCopyMemorySized %79 %44 %21 Aligned 8
; CHECK-NEXT:    %204 = OpBitcast %27 %80
; CHECK-NEXT:    OpLifetimeStart %204 80
; CHECK-NEXT:    %205 = OpLoad %12 %77
; CHECK-NEXT:    %206 = OpBuildNDRange %9 %205 %14 %14
; CHECK-NEXT:    OpStore %80 %206
; CHECK-NEXT:    %207 = OpBitcast %27 %80
; CHECK-NEXT:    OpLifetimeStop %207 80
; CHECK-NEXT:    %208 = OpBitcast %27 %81
; CHECK-NEXT:    OpLifetimeStart %208 80
; CHECK-NEXT:    %209 = OpBitcast %15 %77
; CHECK-NEXT:    %210 = OpBitcast %13 %209
; CHECK-NEXT:    %211 = OpLoad %12 %210
; CHECK-NEXT:    %212 = OpLoad %12 %78
; CHECK-NEXT:    %213 = OpBuildNDRange %9 %211 %212 %14
; CHECK-NEXT:    OpStore %81 %213
; CHECK-NEXT:    %214 = OpBitcast %27 %81
; CHECK-NEXT:    OpLifetimeStop %214 80
; CHECK-NEXT:    %215 = OpBitcast %27 %82
; CHECK-NEXT:    OpLifetimeStart %215 80
; CHECK-NEXT:    %216 = OpBitcast %15 %79
; CHECK-NEXT:    %217 = OpBitcast %13 %209
; CHECK-NEXT:    %218 = OpLoad %12 %217
; CHECK-NEXT:    %219 = OpLoad %12 %78
; CHECK-NEXT:    %220 = OpBitcast %13 %216
; CHECK-NEXT:    %221 = OpLoad %12 %220
; CHECK-NEXT:    %222 = OpBuildNDRange %9 %218 %219 %221
; CHECK-NEXT:    OpStore %82 %222
; CHECK-NEXT:    %223 = OpBitcast %27 %82
; CHECK-NEXT:    OpLifetimeStop %223 80
; CHECK-NEXT:    %224 = OpBitcast %27 %83
; CHECK-NEXT:    OpLifetimeStart %224 80
; CHECK-NEXT:    %225 = OpBitcast %13 %209
; CHECK-NEXT:    %226 = OpLoad %12 %225
; CHECK-NEXT:    %227 = OpLoad %12 %77
; CHECK-NEXT:    %228 = OpBuildNDRange %9 %226 %227 %14
; CHECK-NEXT:    OpStore %83 %228
; CHECK-NEXT:    %229 = OpBitcast %27 %83
; CHECK-NEXT:    OpLifetimeStop %229 80
; CHECK-NEXT:    %230 = OpBitcast %27 %84
; CHECK-NEXT:    OpLifetimeStart %230 80
; CHECK-NEXT:    %231 = OpBitcast %13 %209
; CHECK-NEXT:    %232 = OpLoad %12 %231
; CHECK-NEXT:    %233 = OpLoad %12 %77
; CHECK-NEXT:    %234 = OpBitcast %13 %209
; CHECK-NEXT:    %235 = OpLoad %12 %234
; CHECK-NEXT:    %236 = OpBuildNDRange %9 %232 %233 %235
; CHECK-NEXT:    OpStore %84 %236
; CHECK-NEXT:    %237 = OpBitcast %27 %84
; CHECK-NEXT:    OpLifetimeStop %237 80
; CHECK-NEXT:    %238 = OpBitcast %27 %85
; CHECK-NEXT:    OpLifetimeStart %238 24
; CHECK-NEXT:    OpCopyMemorySized %85 %45 %20 Aligned 8
; CHECK-NEXT:    %239 = OpBitcast %27 %86
; CHECK-NEXT:    OpLifetimeStart %239 24
; CHECK-NEXT:    OpCopyMemorySized %86 %47 %20 Aligned 8
; CHECK-NEXT:    %240 = OpBitcast %27 %87
; CHECK-NEXT:    OpLifetimeStart %240 24
; CHECK-NEXT:    OpCopyMemorySized %87 %49 %20 Aligned 8
; CHECK-NEXT:    %241 = OpBitcast %27 %88
; CHECK-NEXT:    OpLifetimeStart %241 80
; CHECK-NEXT:    %242 = OpLoad %8 %85
; CHECK-NEXT:    %243 = OpBuildNDRange %9 %242 %17 %17
; CHECK-NEXT:    OpStore %88 %243
; CHECK-NEXT:    %244 = OpBitcast %27 %88
; CHECK-NEXT:    OpLifetimeStop %244 80
; CHECK-NEXT:    %245 = OpBitcast %27 %89
; CHECK-NEXT:    OpLifetimeStart %245 80
; CHECK-NEXT:    %246 = OpBitcast %15 %85
; CHECK-NEXT:    %247 = OpBitcast %13 %246
; CHECK-NEXT:    %248 = OpLoad %12 %247
; CHECK-NEXT:    %249 = OpBitcast %13 %86
; CHECK-NEXT:    %250 = OpLoad %12 %249
; CHECK-NEXT:    %251 = OpBuildNDRange %9 %248 %250 %14
; CHECK-NEXT:    OpStore %89 %251
; CHECK-NEXT:    %252 = OpBitcast %27 %89
; CHECK-NEXT:    OpLifetimeStop %252 80
; CHECK-NEXT:    %253 = OpBitcast %27 %90
; CHECK-NEXT:    OpLifetimeStart %253 80
; CHECK-NEXT:    %254 = OpBitcast %15 %87
; CHECK-NEXT:    %255 = OpBitcast %13 %246
; CHECK-NEXT:    %256 = OpLoad %12 %255
; CHECK-NEXT:    %257 = OpBitcast %13 %86
; CHECK-NEXT:    %258 = OpLoad %12 %257
; CHECK-NEXT:    %259 = OpBitcast %13 %254
; CHECK-NEXT:    %260 = OpLoad %12 %259
; CHECK-NEXT:    %261 = OpBuildNDRange %9 %256 %258 %260
; CHECK-NEXT:    OpStore %90 %261
; CHECK-NEXT:    %262 = OpBitcast %27 %90
; CHECK-NEXT:    OpLifetimeStop %262 80
; CHECK-NEXT:    %263 = OpBitcast %27 %91
; CHECK-NEXT:    OpLifetimeStart %263 80
; CHECK-NEXT:    %264 = OpBitcast %13 %246
; CHECK-NEXT:    %265 = OpLoad %12 %264
; CHECK-NEXT:    %266 = OpBitcast %13 %85
; CHECK-NEXT:    %267 = OpLoad %12 %266
; CHECK-NEXT:    %268 = OpBuildNDRange %9 %265 %267 %14
; CHECK-NEXT:    OpStore %91 %268
; CHECK-NEXT:    %269 = OpBitcast %27 %91
; CHECK-NEXT:    OpLifetimeStop %269 80
; CHECK-NEXT:    %270 = OpBitcast %27 %92
; CHECK-NEXT:    OpLifetimeStart %270 80
; CHECK-NEXT:    %271 = OpBitcast %13 %246
; CHECK-NEXT:    %272 = OpLoad %12 %271
; CHECK-NEXT:    %273 = OpBitcast %13 %85
; CHECK-NEXT:    %274 = OpLoad %12 %273
; CHECK-NEXT:    %275 = OpBitcast %13 %246
; CHECK-NEXT:    %276 = OpLoad %12 %275
; CHECK-NEXT:    %277 = OpBuildNDRange %9 %272 %274 %276
; CHECK-NEXT:    OpStore %92 %277
; CHECK-NEXT:    %278 = OpBitcast %27 %92
; CHECK-NEXT:    OpLifetimeStop %278 80
; CHECK-NEXT:    %279 = OpBitcast %27 %87
; CHECK-NEXT:    OpLifetimeStop %279 24
; CHECK-NEXT:    %280 = OpBitcast %27 %86
; CHECK-NEXT:    OpLifetimeStop %280 24
; CHECK-NEXT:    %281 = OpBitcast %27 %85
; CHECK-NEXT:    OpLifetimeStop %281 24
; CHECK-NEXT:    %282 = OpBitcast %27 %79
; CHECK-NEXT:    OpLifetimeStop %282 16
; CHECK-NEXT:    %283 = OpBitcast %27 %78
; CHECK-NEXT:    OpLifetimeStop %283 16
; CHECK-NEXT:    %284 = OpBitcast %27 %77
; CHECK-NEXT:    OpLifetimeStop %284 16
; CHECK-NEXT:    %285 = OpBitcast %27 %66
; CHECK-NEXT:    OpLifetimeStop %285 24
; CHECK-NEXT:    %286 = OpBitcast %27 %65
; CHECK-NEXT:    OpLifetimeStop %286 24
; CHECK-NEXT:    %287 = OpBitcast %27 %64
; CHECK-NEXT:    OpLifetimeStop %287 24
; CHECK-NEXT:    %288 = OpBitcast %27 %58
; CHECK-NEXT:    OpLifetimeStop %288 16
; CHECK-NEXT:    %289 = OpBitcast %27 %57
; CHECK-NEXT:    OpLifetimeStop %289 16
; CHECK-NEXT:    %290 = OpBitcast %27 %56
; CHECK-NEXT:    OpLifetimeStop %290 16
; CHECK-NEXT:    OpReturn
; CHECK-NEXT:    OpFunctionEnd
entry:
  %tmp = alloca %struct.ndrange_t, align 8
  %tmp1 = alloca %struct.ndrange_t, align 8
  %tmp2 = alloca %struct.ndrange_t, align 8
  %tmp3 = alloca %struct.ndrange_t, align 8
  %tmp4 = alloca %struct.ndrange_t, align 8
  %GS2 = alloca [2 x i64], align 8
  %LS2 = alloca [2 x i64], align 8
  %WO2 = alloca [2 x i64], align 8
  %tmp5 = alloca %struct.ndrange_t, align 8
  %tmp8 = alloca %struct.ndrange_t, align 8
  %tmp12 = alloca %struct.ndrange_t, align 8
  %tmp15 = alloca %struct.ndrange_t, align 8
  %tmp19 = alloca %struct.ndrange_t, align 8
  %GS3 = alloca [3 x i64], align 8
  %LS3 = alloca [3 x i64], align 8
  %WO3 = alloca [3 x i64], align 8
  %tmp21 = alloca %struct.ndrange_t, align 8
  %tmp24 = alloca %struct.ndrange_t, align 8
  %tmp28 = alloca %struct.ndrange_t, align 8
  %tmp31 = alloca %struct.ndrange_t, align 8
  %tmp35 = alloca %struct.ndrange_t, align 8
  %tmp36 = alloca %struct.ndrange_t, align 8
  %tmp37 = alloca %struct.ndrange_t, align 8
  %tmp38 = alloca %struct.ndrange_t, align 8
  %tmp39 = alloca %struct.ndrange_t, align 8
  %tmp40 = alloca %struct.ndrange_t, align 8
  %GS2c = alloca [2 x i64], align 8
  %LS2c = alloca [2 x i64], align 8
  %WO2c = alloca [2 x i64], align 8
  %tmp42 = alloca %struct.ndrange_t, align 8
  %tmp45 = alloca %struct.ndrange_t, align 8
  %tmp49 = alloca %struct.ndrange_t, align 8
  %tmp52 = alloca %struct.ndrange_t, align 8
  %tmp56 = alloca %struct.ndrange_t, align 8
  %GS3c = alloca [3 x i64], align 8
  %LS3c = alloca [3 x i64], align 8
  %WO3c = alloca [3 x i64], align 8
  %tmp58 = alloca %struct.ndrange_t, align 8
  %tmp61 = alloca %struct.ndrange_t, align 8
  %tmp65 = alloca %struct.ndrange_t, align 8
  %tmp68 = alloca %struct.ndrange_t, align 8
  %tmp72 = alloca %struct.ndrange_t, align 8
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp) #4
  call spir_func void @_Z10ndrange_1Dm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp, i64 noundef 1) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp1) #4
  call spir_func void @_Z10ndrange_1Dmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp1, i64 noundef 1, i64 noundef 2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp1) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp2) #4
  call spir_func void @_Z10ndrange_1Dmmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp2, i64 noundef 3, i64 noundef 1, i64 noundef 2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp2) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp3) #4
  call spir_func void @_Z10ndrange_1Dmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp3, i64 noundef 1, i64 noundef 1) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp3) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp4) #4
  call spir_func void @_Z10ndrange_1Dmmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp4, i64 noundef 1, i64 noundef 1, i64 noundef 1) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp4) #4
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %GS2) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(16) %GS2, ptr addrspace(2) noundef align 8 dereferenceable(16) @__const.test_ndrange_2D3D.GS2, i64 16, i1 false)
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %LS2) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(16) %LS2, ptr addrspace(2) noundef align 8 dereferenceable(16) @__const.test_ndrange_2D3D.LS2, i64 16, i1 false)
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %WO2) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(16) %WO2, ptr addrspace(2) noundef align 8 dereferenceable(16) @__const.test_ndrange_2D3D.WO2, i64 16, i1 false)
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp5) #4
  call spir_func void @_Z10ndrange_2DPKm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp5, ptr noundef nonnull %GS2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp5) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp8) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp8, ptr noundef nonnull %GS2, ptr noundef nonnull %LS2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp8) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp12) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp12, ptr noundef nonnull %WO2, ptr noundef nonnull %GS2, ptr noundef nonnull %LS2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp12) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp15) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp15, ptr noundef nonnull %GS2, ptr noundef nonnull %GS2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp15) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp19) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp19, ptr noundef nonnull %GS2, ptr noundef nonnull %GS2, ptr noundef nonnull %GS2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp19) #4
  call void @llvm.lifetime.start.p0(i64 24, ptr nonnull %GS3) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(24) %GS3, ptr addrspace(2) noundef align 8 dereferenceable(24) @__const.test_ndrange_2D3D.GS3, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 24, ptr nonnull %LS3) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(24) %LS3, ptr addrspace(2) noundef align 8 dereferenceable(24) @__const.test_ndrange_2D3D.LS3, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 24, ptr nonnull %WO3) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(24) %WO3, ptr addrspace(2) noundef align 8 dereferenceable(24) @__const.test_ndrange_2D3D.WO3, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp21) #4
  call spir_func void @_Z10ndrange_3DPKm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp21, ptr noundef nonnull %GS3) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp21) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp24) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp24, ptr noundef nonnull %GS3, ptr noundef nonnull %LS3) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp24) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp28) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp28, ptr noundef nonnull %WO3, ptr noundef nonnull %GS3, ptr noundef nonnull %LS3) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp28) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp31) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp31, ptr noundef nonnull %GS3, ptr noundef nonnull %GS3) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp31) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp35) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp35, ptr noundef nonnull %GS3, ptr noundef nonnull %GS3, ptr noundef nonnull %GS3) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp35) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp36) #4
  call spir_func void @_Z10ndrange_1Dm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp36, i64 noundef 1) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp36) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp37) #4
  call spir_func void @_Z10ndrange_1Dmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp37, i64 noundef 1, i64 noundef 2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp37) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp38) #4
  call spir_func void @_Z10ndrange_1Dmmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp38, i64 noundef 3, i64 noundef 1, i64 noundef 2) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp38) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp39) #4
  call spir_func void @_Z10ndrange_1Dmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp39, i64 noundef 1, i64 noundef 1) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp39) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp40) #4
  call spir_func void @_Z10ndrange_1Dmmm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp40, i64 noundef 1, i64 noundef 1, i64 noundef 1) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp40) #4
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %GS2c) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(16) %GS2c, ptr addrspace(2) noundef align 8 dereferenceable(16) @__const.test_ndrange_2D3D.GS2c, i64 16, i1 false)
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %LS2c) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(16) %LS2c, ptr addrspace(2) noundef align 8 dereferenceable(16) @__const.test_ndrange_2D3D.LS2c, i64 16, i1 false)
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %WO2c) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(16) %WO2c, ptr addrspace(2) noundef align 8 dereferenceable(16) @__const.test_ndrange_2D3D.WO2c, i64 16, i1 false)
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp42) #4
  call spir_func void @_Z10ndrange_2DPKm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp42, ptr noundef nonnull %GS2c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp42) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp45) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp45, ptr noundef nonnull %GS2c, ptr noundef nonnull %LS2c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp45) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp49) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp49, ptr noundef nonnull %WO2c, ptr noundef nonnull %GS2c, ptr noundef nonnull %LS2c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp49) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp52) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp52, ptr noundef nonnull %GS2c, ptr noundef nonnull %GS2c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp52) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp56) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp56, ptr noundef nonnull %GS2c, ptr noundef nonnull %GS2c, ptr noundef nonnull %GS2c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp56) #4
  call void @llvm.lifetime.start.p0(i64 24, ptr nonnull %GS3c) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(24) %GS3c, ptr addrspace(2) noundef align 8 dereferenceable(24) @__const.test_ndrange_2D3D.GS3c, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 24, ptr nonnull %LS3c) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(24) %LS3c, ptr addrspace(2) noundef align 8 dereferenceable(24) @__const.test_ndrange_2D3D.LS3c, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 24, ptr nonnull %WO3c) #4
  call void @llvm.memcpy.p0.p2.i64(ptr noundef nonnull align 8 dereferenceable(24) %WO3c, ptr addrspace(2) noundef align 8 dereferenceable(24) @__const.test_ndrange_2D3D.WO3c, i64 24, i1 false)
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp58) #4
  call spir_func void @_Z10ndrange_3DPKm(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp58, ptr noundef nonnull %GS3c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp58) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp61) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp61, ptr noundef nonnull %GS3c, ptr noundef nonnull %LS3c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp61) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp65) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp65, ptr noundef nonnull %WO3c, ptr noundef nonnull %GS3c, ptr noundef nonnull %LS3c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp65) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp68) #4
  call spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp68, ptr noundef nonnull %GS3c, ptr noundef nonnull %GS3c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp68) #4
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp72) #4
  call spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind nonnull writable sret(%struct.ndrange_t) align 8 %tmp72, ptr noundef nonnull %GS3c, ptr noundef nonnull %GS3c, ptr noundef nonnull %GS3c) #5
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp72) #4
  call void @llvm.lifetime.end.p0(i64 24, ptr nonnull %WO3c) #4
  call void @llvm.lifetime.end.p0(i64 24, ptr nonnull %LS3c) #4
  call void @llvm.lifetime.end.p0(i64 24, ptr nonnull %GS3c) #4
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %WO2c) #4
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %LS2c) #4
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %GS2c) #4
  call void @llvm.lifetime.end.p0(i64 24, ptr nonnull %WO3) #4
  call void @llvm.lifetime.end.p0(i64 24, ptr nonnull %LS3) #4
  call void @llvm.lifetime.end.p0(i64 24, ptr nonnull %GS3) #4
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %WO2) #4
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %LS2) #4
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %GS2) #4
  ret void
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1
declare spir_func void @_Z10ndrange_1Dm(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, i64 noundef) local_unnamed_addr #2
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1
declare spir_func void @_Z10ndrange_1Dmm(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, i64 noundef, i64 noundef) local_unnamed_addr #2
declare spir_func void @_Z10ndrange_1Dmmm(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, i64 noundef, i64 noundef, i64 noundef) local_unnamed_addr #2
declare void @llvm.memcpy.p0.p2.i64(ptr noalias nocapture writeonly, ptr addrspace(2) noalias nocapture readonly, i64, i1 immarg) #3
declare spir_func void @_Z10ndrange_2DPKm(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, ptr noundef) local_unnamed_addr #2
declare spir_func void @_Z10ndrange_2DPKmS0_(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, ptr noundef, ptr noundef) local_unnamed_addr #2
declare spir_func void @_Z10ndrange_2DPKmS0_S0_(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, ptr noundef, ptr noundef, ptr noundef) local_unnamed_addr #2
declare spir_func void @_Z10ndrange_3DPKm(ptr dead_on_unwind writable sret(%struct.ndrange_t) align 8, ptr noundef) local_unnamed_addr #2
