; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6

; RUN: llc -O0 -mtriple=spirv64-unknown-unknown %s -o - | FileCheck %s
; %if spirv-tools %{ llc -O0 -mtriple=spirv64-unknown-unknown %s -o - -filetype=obj | spirv-val %}


%struct.ndrange_t = type { i32, [3 x i64], [3 x i64], [3 x i64] }

define spir_func void @test_ndrange_2D3D() local_unnamed_addr #0 {
; CHECK-LABEL: test_ndrange_2D3D
; CHECK:       Begin function test_ndrange_2D3D
; CHECK:       %[[#r18:]] = OpBuildNDRange %[[#r10:]] %[[#r11:]] %[[#r12:]] %[[#r13:]]
; CHECK-NOT:    OpStore %[[#r19:]] %[[#r18]]
entry:
  %tmp = alloca %struct.ndrange_t, align 8
  call void @llvm.lifetime.start.p0(i64 80, ptr nonnull %tmp) #3
  call spir_func %struct.ndrange_t @_Z10ndrange_1Dm(i64 noundef 1) #4
  call void @llvm.lifetime.end.p0(i64 80, ptr nonnull %tmp) #3
  ret void
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

declare spir_func %struct.ndrange_t  @_Z10ndrange_1Dm(i64 noundef) local_unnamed_addr #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1
